version: '3.8'

services:
  proynode:
    container_name: proynode
    build: .
    env_file:
      - ./.env
    ports:
      - "$PORT:$PORT"
    environment:
      - PORT=$PORT
    depends_on:
      - bd_mysql

  bd_mysql:
    container_name: bd_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./data:/var/lib/mysql

  webserver:
    container_name: webserver
    image: nginx:1.25.5-alpine
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/etc/lib/letsencrypt
    depends_on:
      - proynode
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/etc/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email alfredoguillenpinto@gmail.com --agree-tos -d apinode.curso-docker.store
    depends_on:
      - webserver
    

#  certbot:
volumes:
  web-root:
  certbot-etc:
  certbot-var:
